# Generated by Django 4.0.6 on 2022-09-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('customer_creditscore', models.IntegerField(blank=True, null=True)),
                ('customer_req_loanamount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
    ]
